project:
  type: book

filters:
  - shinylive

book:
  title: "."
  author: "Norah Jones"
  date: "6/10/2023"
  chapters:
    - index.qmd
    - part: Deep Learning Specialization
      chapters: 
        - Convolutional_Neural_Networks.ipynb
    - intro.qmd
    - sine_wave.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

