on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Packages
        run: pip install shinylive --upgrade

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTeX
        run: |
          wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
          export PATH=$PATH:$HOME/.TinyTeX/bin/x86_64-linux
          tlmgr install xetex

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}